/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/model` | `/model`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(footer-tabs)'}/activity` | `/activity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(footer-tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(footer-tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(footer-tabs)'}/model` | `/model`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(footer-tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(footer-tabs)'}/activity${`?${string}` | `#${string}` | ''}` | `/activity${`?${string}` | `#${string}` | ''}` | `${'/(footer-tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(footer-tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(footer-tabs)'}/model${`?${string}` | `#${string}` | ''}` | `/model${`?${string}` | `#${string}` | ''}` | `${'/(footer-tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/model` | `/model`; params?: Router.UnknownInputParams; } | { pathname: `${'/(footer-tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
